[package]
name = "yew-markdown"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
pulldown-cmark = "0.9.2"
yew = "0.19.3"
